# This script contains the logic for the analytics development notebook.
# You can copy and paste the code from each section into the cells
# of a new Jupyter Notebook (`.ipynb`) file.

# --- Cell 1: Setup and Imports ---
import duckdb
import pandas as pd
from pathlib import Path

# Define the path to the DuckDB database file generated by dbt
# This path is relative to the 'analytics' directory.
DB_PATH = '../pipelines/data_lake/prod.duckdb'

# Connect to the database
con = duckdb.connect(database=str(DB_PATH), read_only=True)
print("Successfully connected to the dbt data warehouse.")

# --- Cell 2: List Available Models ---
print("\n--- Available Tables/Models in 'main' schema ---")
print(con.execute("SHOW TABLES").df())

# --- Cell 3: Load the `all_transactions_by_customer` Model ---
print("\n--- Loading 'all_transactions_by_customer' model ---")
transactions_df = con.execute("SELECT * FROM main.all_transactions_by_customer").df()
print("Schema:")
transactions_df.info()
print("\nFirst 5 rows:")
print(transactions_df.head())

# --- Cell 4: Ad-Hoc Analysis & Prototyping ---
print("\n--- Ad-Hoc Query: Total Withdrawals per Customer ---")
query = """
SELECT 
    email, 
    SUM(withdrawals) as total_withdrawals
FROM main.all_transactions_by_customer
GROUP BY email
ORDER BY total_withdrawals DESC
"""
print(con.execute(query).df())

# --- Cell 5: Closing the Connection ---
con.close()
print("\nDatabase connection closed.") 
