# dbt_transformations/profiles.yml

customer_transactions_profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DATA_LAKE_ROOT', '..') }}/data_lake/dbt.duckdb"
      schema: main
      extensions:
        - delta
      # Optional: add extensions here
      # extensions:
      #   - httpfs
      #   - a_n_other
