version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount the local 'app' directory into the container's 'app' directory
      - ./api_mock:/app/api_mock
      - ./run.py:/app/run.py
    environment:
      # This tells Flask to run in development mode
      - FLASK_ENV=development
