version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount the local 'app' directory into the container's 'app' directory
      - ./app:/app/app
      # You can also mount the data directory if you want to make changes to CSVs
      - ./data:/app/data
    environment:
      # This tells Flask to run in development mode
      - FLASK_ENV=development
