services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "5000:5000"
    volumes:
      # Mount the local 'app' directory into the container's 'app' directory
      - ./api_mock:/app/api_mock
      - ./config.json:/app/config.json
      - ./run.py:/app/run.py
    environment:
      - FLASK_APP=run.py
      # This tells Flask to run in development mode
      - FLASK_ENV=development

  underwriter_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: underwriter_app
    ports:
      - "8501:8501"
    volumes:
      # Mount the code and config so changes are reflected without rebuilding
      - ./underwriter_app.py:/app/underwriter_app.py
      - ./config.json:/app/config.json
      - ./pipelines:/app/pipelines
      - ./analytics:/app/analytics
      # Mount the data lake directory to persist data artifacts
      - ./data_lake:/app/data_lake
    depends_on:
      - api
    environment:
      # This ensures dbt in the container writes to the host filesystem via the volume mount
      - PWD=/app
      # This variable tells the application where the root directory is inside the container.
      - DATA_LAKE_ROOT=/app
