version: 2

models:
  - name: stg_transactions
    description: "This model is the entry point for raw transaction data into the dbt project. It directly reads the 'silver' layer of the data lake, which contains the combined, cleansed, and deduplicated transaction data from all source bank statements. The data is loaded from the Silver Delta table using DuckDB's `delta_scan()` function, which efficiently reads the latest version of the data directly from the Delta Lake transaction log. This process is orchestrated by the `transform_statements.py` pipeline, which reads from the Bronze layer, cleans the data, and merges it into the Silver table, ensuring data integrity and idempotency. This model serves as the foundational source table for all downstream analysis and financial metric calculations."
    columns:
      - name: account_balance
        description: "The total balance of the bank account at the moment the data was fetched from the source. e.g., 418.52"
      - name: account_name
        description: "The specific name of the bank account as provided by the financial institution. e.g., 'No Fee Chequing Account'."
      - name: account_number
        description: "The unique identifier for the bank account. This is a critical field for joining data and identifying unique accounts. e.g., '010-30800-0095983938'."
      - name: account_type
        description: "A high-level classification of the bank account. e.g., 'Operation'."
      - name: address
        description: "The physical address of the account holder. e.g., '36 HOLKHAM AVE, ANCASTER, ON, L9K1P1'."
      - name: amount
        description: "A calculated field representing the value of the transaction. It is positive for credits/deposits and negative for debits/withdrawals. This normalizes the 'deposits' and 'withdrawals' columns into a single, consistent field."
      - name: balance
        description: "The running balance of the account *after* the transaction occurred, as it appears on the statement. e.g., '418.52'."
      - name: category
        description: "A high-level category assigned to the transaction, typically indicating the direction of money flow. e.g., 'debit'."
      - name: date
        description: "The date on which the transaction was processed by the bank. e.g., '2024-02-09'."
      - name: days_detected
        description: "A field from the source system, potentially used to indicate the age or detection date of the transaction. (Often requires more context from the source API documentation)."
      - name: deposits
        description: "The original, raw value of a deposit from the source data. This field is kept for auditing and data lineage purposes. It is mutually exclusive with 'withdrawals'."
      - name: description
        description: "The raw, unprocessed transaction description from the bank statement. This is a key field for transaction categorization. e.g., 'MISCELLANEOUS PAYMENTS NEWFOUNDLAND POWER INC.'."
      - name: email
        description: "The email address of the account holder. It's important to note this may arrive in uppercase and should be normalized for consistency. e.g., 'JOELSCHAUBEL@GMAIL.COM'."
      - name: employer_name
        description: "The name of the account holder's employer, if available in the source data."
      - name: financial_institution
        description: "The name of the bank or financial institution where the account is held. e.g., 'Simplii'."
      - name: login_id
        description: "A unique identifier for the authentication session with the source API (Flinks mock). e.g., '5eff116b-d0d9-4924-4b37-08dc29c779f9'."
      - name: request_date_time
        description: "The specific timestamp when the data request was made to the source API. e.g., '2024-02-11 19:26:39'."
      - name: request_id
        description: "The unique identifier for the entire data retrieval process or job. This is crucial for tracking data lineage. e.g., '727DAE61-63E9-4121-801E-F11CA8FF32FD'."
        tests:
          - not_null
      - name: request_status
        description: "The final status of the data request from the source API. e.g., 'Get Statements Completed'."
      - name: subcategory
        description: "A more granular category for the transaction, if available."
      - name: tag
        description: "A flexible metadata field containing various key-value pairs related to the request context from the source system. e.g., 'email=...,businessId=...,userId=...'."
      - name: type
        description: "The type of transaction (e.g., 'credit', 'debit'). This column often duplicates information found in the 'category' field and may require consolidation in downstream models."
      - name: username
        description: "The full name of the account holder. e.g., 'Joel Schaubel'."
      - name: withdrawals
        description: "The original, raw value of a withdrawal from the source data. This field is kept for auditing and is mutually exclusive with 'deposits'."
      - name: account_id
        description: "An internal identifier assigned to the account, used for joining and tracking within the data warehouse. This may differ from the public-facing 'account_number'."

  - name: int_transactions_enriched
    description: "This model is the foundational table for all customer transactions. It reads from the `statements` model and enriches the data with key analytical columns. The model's primary logic involves using a window function to determine the most recent transaction date for each data pull (`request_id`), which serves as a consistent anchor for time-based calculations. It then casts data to the correct types, creates boolean flags for revenue and debits, and generates a series of lookback date columns (e.g., last 30, 90, 180, 365 days) to simplify downstream financial metric calculations. This table serves as the primary source for all subsequent analysis."
    columns:
      - name: username
        description: "The full name of the account holder. e.g., 'Joel Schaubel'."
      - name: email
        description: "The email address of the account holder. It's important to note this may arrive in uppercase and should be normalized for consistency. e.g., 'JOELSCHAUBEL@GMAIL.COM'."
      - name: address
        description: "The physical address of the account holder. e.g., '36 HOLKHAM AVE, ANCASTER, ON, L9K1P1'."
      - name: financial_institution
        description: "The name of the bank or financial institution where the account is held. e.g., 'Simplii'."
      - name: employer_name
        description: "The name of the account holder's employer, if available in the source data."
      - name: login_id
        description: "A unique identifier for the authentication session with the source API (Flinks mock). e.g., '5eff116b-d0d9-4924-4b37-08dc29c779f9'."
      - name: request_id
        description: "The unique identifier for the entire data retrieval process or job. This is crucial for tracking data lineage. e.g., '727DAE61-63E9-4121-801E-F11CA8FF32FD'."
      - name: request_datetime
        description: "The specific timestamp when the data request was made to the source API. This column is an alias for `request_date_time` from the source model. e.g., '2024-02-11 19:26:39'."
      - name: request_status
        description: "The final status of the data request from the source API. e.g., 'Get Statements Completed'."
      - name: days_detected
        description: "A field from the source system, potentially used to indicate the age or detection date of the transaction. (Often requires more context from the source API documentation)."
      - name: tag
        description: "A flexible metadata field containing various key-value pairs related to the request context from the source system. e.g., 'email=...,businessId=...,userId=...'."
      - name: account_name
        description: "The specific name of the bank account as provided by the financial institution. e.g., 'No Fee Chequing Account'."
      - name: account_number
        description: "The unique identifier for the bank account. This is a critical field for joining data and identifying unique accounts. e.g., '010-30800-0095983938'."
      - name: account_type
        description: "A high-level classification of the bank account. e.g., 'Operation'."
      - name: account_balance
        description: "The total balance of the bank account at the moment the data was fetched from the source. e.g., 418.52"
      - name: date
        description: "The date on which the transaction was processed by the bank. e.g., '2024-02-09'."
      - name: description
        description: "The raw, unprocessed transaction description from the bank statement. This is a key field for transaction categorization. e.g., 'MISCELLANEOUS PAYMENTS NEWFOUNDLAND POWER INC.'."
      - name: category
        description: "A high-level category assigned to the transaction, typically indicating the direction of money flow. e.g., 'debit'."
      - name: subcategory
        description: "A more granular category for the transaction, if available."
      - name: withdrawals
        description: "The original, raw value of a withdrawal from the source data. This field is kept for auditing and is mutually exclusive with 'deposits'."
      - name: deposits
        description: "The original, raw value of a deposit from the source data. This field is kept for auditing and data lineage purposes. It is mutually exclusive with 'withdrawals'."
      - name: balance
        description: "The running balance of the account *after* the transaction occurred, as it appears on the statement. e.g., '418.52'."
      - name: is_revenue
        description: "A boolean flag (TRUE/FALSE) calculated in this model. It is TRUE if the 'deposits' column has a value greater than zero."
      - name: is_debit
        description: "A boolean flag (TRUE/FALSE) calculated in this model. It is TRUE if the 'withdrawals' column has a value greater than zero. e.g., TRUE."
      - name: most_recent_statement_date
        description: "The latest transaction date for a given 'request_id', calculated using a window function. This serves as the anchor date for all time-based analysis. e.g., '2024-02-09'."
      - name: most_recent_statement_date_minus_30_days
        description: "A calculated date marker for 30 days prior to the 'most_recent_statement_date'. e.g., '2024-01-10'."
      - name: most_recent_statement_date_minus_60_days
        description: "A calculated date marker for 60 days prior to the 'most_recent_statement_date'. e.g., '2023-12-11'."
      - name: most_recent_statement_date_minus_90_days
        description: "A calculated date marker for 90 days prior to the 'most_recent_statement_date'. e.g., '2023-11-11'."
      - name: most_recent_statement_date_minus_180_days
        description: "A calculated date marker for 180 days prior to the 'most_recent_statement_date'. e.g., '2023-08-13'."
      - name: most_recent_statement_date_minus_365_days
        description: "A calculated date marker for 365 days prior to the 'most_recent_statement_date'. e.g., '2023-02-09'."

